apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: hmsacrstudent001.azurecr.io/health-monitoring-worker:latest
        imagePullPolicy: Always
        env:
        - name: DOTNET_ENVIRONMENT
          value: "Production"
        - name: JOB
          value: "process-monitoring"
        - name: JOB_INTERVAL_SEC
          value: "60"
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: defaultConnection-secret